// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.tsx</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             target="_blank"
//             rel="noopener noreferrer"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }

// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
// import logo from './logo.svg';
// import Link from 'next/link';
// import {Routes,Route} from "react-router-dom"
// import Home from './pages/Home';
// import Collection from './pages/Collections';
// import CreateNft from './pages/createNft';
// import Layout from '../components/layout';
// import YourNft from './pages/yourNft';
// import Bid from './pages/bid';
// function App() {
//   return (
//     <div className="App">
//       <Layout>
//         <Link href='/' />
//         <Link href='/collections' />
//         <Link href='/createnft' />
//         <Link href='/yourNft' />
//         <Link href='/bid/:id' />
//       </Layout>
//     </div>
//   );
// }

// export default App;

{
  /* <Common
        imgsrc={"/assets/Pictures/mic.jpg"}
        visit="/collections"
      /> */
}

//

import React from "react";
import { useMoralis } from "react-moralis";
// import Common from "../components/Common";
// import mic from "../assets/Pictures/mic.jpg";
// import heroImg from "../../assests/Pictures/img2.png"
// import Avatar from "@mui/material/Avatar";
// import team1 from "../../assests/Pictures/team1.jpg"
// import team2 from "../../assests/Pictures/team2.jpeg"
// import team3 from "../../assests/Pictures/team3.jpg"
import { MdEmail } from "react-icons/md";
import { AiFillGithub } from "react-icons/ai";
import { FaDiscord } from "react-icons/fa";
import { Divider, Button, Container } from "@mui/material";
import Link from "next/link";
import ConnectAccount from "../components/ConnectAccount";
import { Grid, Box, Typography, Stack, Card, CardMedia, CardContent } from "@mui/material";
import Gallery from "../components/Gallery";

function Index() {
  const { account, isAuthenticated } = useMoralis();

  return (
    <main className="relative min-h-screen bg-white sm:flex sm:items-center sm:justify-center">
      <Grid container>
        <Grid item xs={12} md={6}>
          <Stack>
            <Container maxWidth="sm">
              <Typography variant="h3" gutterBottom fontWeight="bold" color="purple" sx={{ mt: 4 }}>
                {" "}
                Decentralized Music gallery powered by Polygon{" "}
              </Typography>
              <Typography paragraph sx={{ fontSize: "16px", fontWeight: "bold" }}>
                Access and download old and latest music of your choice.
              </Typography>
              <div className="container">
                <ul>
                  <Typography>No credit card hassle</Typography>
                  <Typography>Secure download and file integrity</Typography>
                  <Typography>Earn each time your music is downloaded</Typography>
                  <Typography>Access high quality music at extremely cheaper fee</Typography>
                </ul>
              </div>
              <Divider />
              <Button
                variant="outlined"
                sx={{
                  height: "58px",
                  width: "50%",
                  mt: 2,
                  background: "none",
                  borderColor: "purple",
                  "&:hover": {
                    transition: "0.2s ease-in-out",
                    zIndex: "1",
                    color: "purple",
                    background: "stone"
                  }
                }}
              >
                <Link href={"/upload"}>Upload</Link>
              </Button>
            </Container>
          </Stack>
        </Grid>
        <Grid item xs={12} md={6}>
          <Box>
            <img className="h-full w-full object-cover" src="https://user-images.githubusercontent.com/1500684/157774694-99820c51-8165-4908-a031-34fc371ac0d6.jpg" alt="Sonic Youth On Stage" />
          </Box>
        </Grid>
      </Grid>
      <Divider />
      <Gallery />
    </main>
  );
}

export default Index;

{
  /* <img src={team1} alt=""  className='h-20 w-20 rounded-full'/> */
}
{
  /* <div className='team flex flex-col justify-center items-center py-12 px-16'>
<Typography variant='h5' className='text-purple-600 font-semibold pb-4'>Gallery</Typography>
<Grid container spacing={2}>
  <Grid item xs={12} md={4} >
    <Box>
      <Card sx={{}}>
        <Grid item container xs={12}>
          <Grid item xs={5}>
            <CardMedia component="img" sx={{p: 4, width: '100%', height: '100%' }} image={"/team1.jpg"} alt="random" className='rounded-full'/>
          </Grid>
          <Grid item xs={7} className='shadow-lg'>
            <CardContent sx={{ flexGrow: 1, }} >
              <Stack sx={{ }}>
                <Typography gutterBottom variant="h5" className='text-sm text-purple-400'>Frontend Developer</Typography>
                <Typography variant='body1' gutterBottom className='text-lg font-semibold'>{"Oliviahotakwa"}</Typography>
                <Typography className='text-xs'>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo atque minima ipsum maxime possimus error cupiditate a libero ipsa?</Typography>
                <Box sx={{display: 'flex', justifyContent: 'center', alignItems: 'center', gap: 2, pt: 2 }}>
                  <MdEmail className="text-slate-500 cursor-pointer  text-lg" />
                  <AiFillGithub className="text-slate-500 cursor-pointer  text-lg"/>
                  <FaDiscord className="text-slate-500 cursor-pointer  text-lg"/>
                </Box>
              </Stack>
            </CardContent>
          </Grid>
        </Grid>
      </Card>
    </Box>
  </Grid>

  <Grid item xs={12} md={4}>
    {/* <Grid item xs={12} md={4} > */
}
//       <Box>
//         <Card sx={{}}>
//           <Grid item container xs={12}>
//             <Grid item xs={5}><CardMedia component="img" sx={{p: 4, width: '100%', height: '100%' }} image={"/team2.jpeg"} alt="random" className='rounded-full'/></Grid>
//             <Grid item xs={7}>
//               <CardContent sx={{ flexGrow: 1, }} >
//                 <Stack sx={{ }}>
//                   <Typography gutterBottom variant="h5" className='text-sm text-purple-400'>Fullstack Developer</Typography>
//                   <Typography variant='body1' gutterBottom className='text-lg font-semibold'>{"Scapula "}</Typography>
//                   <Typography className='text-xs'>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo atque minima ipsum maxime possimus error cupiditate a libero ipsa?</Typography>
//                   <Box sx={{display: 'flex', justifyContent: 'center', alignItems: 'center', gap: 2, pt: 2 }}>
//                     <MdEmail className="text-slate-500 cursor-pointer  text-lg" />
//                     <AiFillGithub className="text-slate-500 cursor-pointer  text-lg"/>
//                     <FaDiscord className="text-slate-500 cursor-pointer  text-lg"/>
//                   </Box>
//                 </Stack>
//               </CardContent>
//             </Grid>
//           </Grid>
//         </Card>
//       </Box>
//     {/* </Grid> */}
//   </Grid>
